// <auto-generated />
using ConsoleArchivist.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleArchivist.Migrations
{
    [DbContext(typeof(ArchivistDbContext))]
    [Migration("20240202205214_CreateTranslationsTable")]
    partial class CreateTranslationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("ConsoleArchivist.Models.Db.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GPTTranslationInYaml")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InGitHub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("IsAGoodTranslation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsToSentToGitHub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LangTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Afar aa"
                        },
                        new
                        {
                            Id = 2,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Afrikaans af"
                        },
                        new
                        {
                            Id = 3,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Akan ak"
                        },
                        new
                        {
                            Id = 4,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Albanian sq"
                        },
                        new
                        {
                            Id = 5,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Amharic am"
                        },
                        new
                        {
                            Id = 6,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Arabic ar"
                        },
                        new
                        {
                            Id = 7,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Aragonese an"
                        },
                        new
                        {
                            Id = 8,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Armenian hy"
                        },
                        new
                        {
                            Id = 9,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Assamese as"
                        },
                        new
                        {
                            Id = 10,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Avaric av"
                        },
                        new
                        {
                            Id = 11,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Avestan ae"
                        },
                        new
                        {
                            Id = 12,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Aymara ay"
                        },
                        new
                        {
                            Id = 13,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Azerbaijani az"
                        },
                        new
                        {
                            Id = 14,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Bambara bm"
                        },
                        new
                        {
                            Id = 15,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Bashkir ba"
                        },
                        new
                        {
                            Id = 16,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Basque eu"
                        },
                        new
                        {
                            Id = 17,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Belarusian be"
                        },
                        new
                        {
                            Id = 18,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Bengali (Bangla) bn"
                        },
                        new
                        {
                            Id = 19,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Bihari bh"
                        },
                        new
                        {
                            Id = 20,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Bislama bi"
                        },
                        new
                        {
                            Id = 21,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Bosnian bs"
                        },
                        new
                        {
                            Id = 22,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Breton br"
                        },
                        new
                        {
                            Id = 23,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Bulgarian bg"
                        },
                        new
                        {
                            Id = 24,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Burmese my"
                        },
                        new
                        {
                            Id = 25,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Catalan ca"
                        },
                        new
                        {
                            Id = 26,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Chamorro ch"
                        },
                        new
                        {
                            Id = 27,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Chechen ce"
                        },
                        new
                        {
                            Id = 28,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Chichewa, Chewa, Nyanja ny"
                        },
                        new
                        {
                            Id = 29,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Chinese zh"
                        },
                        new
                        {
                            Id = 30,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Chinese (Simplified) zh-Hans"
                        },
                        new
                        {
                            Id = 31,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Chinese (Traditional) zh-Hant"
                        },
                        new
                        {
                            Id = 32,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Chuvash cv"
                        },
                        new
                        {
                            Id = 33,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Cornish kw"
                        },
                        new
                        {
                            Id = 34,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Corsican co"
                        },
                        new
                        {
                            Id = 35,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Cree cr"
                        },
                        new
                        {
                            Id = 36,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Croatian hr"
                        },
                        new
                        {
                            Id = 37,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Czech cs"
                        },
                        new
                        {
                            Id = 38,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Danish da"
                        },
                        new
                        {
                            Id = 39,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Divehi, Dhivehi, Maldivian dv"
                        },
                        new
                        {
                            Id = 40,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Dutch nl"
                        },
                        new
                        {
                            Id = 41,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Dzongkha dz"
                        },
                        new
                        {
                            Id = 42,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "English en"
                        },
                        new
                        {
                            Id = 43,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Esperanto eo"
                        },
                        new
                        {
                            Id = 44,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Estonian et"
                        },
                        new
                        {
                            Id = 45,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Ewe ee"
                        },
                        new
                        {
                            Id = 46,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Faroese fo"
                        },
                        new
                        {
                            Id = 47,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Fijian fj"
                        },
                        new
                        {
                            Id = 48,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Finnish fi"
                        },
                        new
                        {
                            Id = 49,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "French fr"
                        },
                        new
                        {
                            Id = 50,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Fula, Fulah, Pulaar, Pular ff"
                        },
                        new
                        {
                            Id = 51,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Galician gl"
                        },
                        new
                        {
                            Id = 52,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Gaelic (Scottish) gd"
                        },
                        new
                        {
                            Id = 53,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Gaelic (Manx) gv"
                        },
                        new
                        {
                            Id = 54,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Georgian ka"
                        },
                        new
                        {
                            Id = 55,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "German de"
                        },
                        new
                        {
                            Id = 56,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Greek el"
                        },
                        new
                        {
                            Id = 57,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Greenlandic kl"
                        },
                        new
                        {
                            Id = 58,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Guarani gn"
                        },
                        new
                        {
                            Id = 59,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Gujarati gu"
                        },
                        new
                        {
                            Id = 60,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Haitian Creole ht"
                        },
                        new
                        {
                            Id = 61,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Hausa ha"
                        },
                        new
                        {
                            Id = 62,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Hebrew he"
                        },
                        new
                        {
                            Id = 63,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Herero hz"
                        },
                        new
                        {
                            Id = 64,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Hindi hi"
                        },
                        new
                        {
                            Id = 65,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Hiri Motu ho"
                        },
                        new
                        {
                            Id = 66,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Hungarian hu"
                        },
                        new
                        {
                            Id = 67,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Icelandic is"
                        },
                        new
                        {
                            Id = 68,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Ido io"
                        },
                        new
                        {
                            Id = 69,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Igbo ig"
                        },
                        new
                        {
                            Id = 70,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Indonesian id, in"
                        },
                        new
                        {
                            Id = 71,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Interlingua ia"
                        },
                        new
                        {
                            Id = 72,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Interlingue ie"
                        },
                        new
                        {
                            Id = 73,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Inuktitut iu"
                        },
                        new
                        {
                            Id = 74,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Inupiak ik"
                        },
                        new
                        {
                            Id = 75,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Irish ga"
                        },
                        new
                        {
                            Id = 76,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Italian it"
                        },
                        new
                        {
                            Id = 77,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Japanese ja"
                        },
                        new
                        {
                            Id = 78,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Javanese jv"
                        },
                        new
                        {
                            Id = 79,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kalaallisut, Greenlandic kl"
                        },
                        new
                        {
                            Id = 80,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kannada kn"
                        },
                        new
                        {
                            Id = 81,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kanuri kr"
                        },
                        new
                        {
                            Id = 82,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kashmiri ks"
                        },
                        new
                        {
                            Id = 83,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kazakh kk"
                        },
                        new
                        {
                            Id = 84,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Khmer km"
                        },
                        new
                        {
                            Id = 85,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kikuyu ki"
                        },
                        new
                        {
                            Id = 86,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kinyarwanda (Rwanda) rw"
                        },
                        new
                        {
                            Id = 87,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kirundi rn"
                        },
                        new
                        {
                            Id = 88,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kyrgyz ky"
                        },
                        new
                        {
                            Id = 89,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Komi kv"
                        },
                        new
                        {
                            Id = 90,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kongo kg"
                        },
                        new
                        {
                            Id = 91,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Korean ko"
                        },
                        new
                        {
                            Id = 92,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kurdish ku"
                        },
                        new
                        {
                            Id = 93,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Kwanyama kj"
                        },
                        new
                        {
                            Id = 94,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Lao lo"
                        },
                        new
                        {
                            Id = 95,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Latin la"
                        },
                        new
                        {
                            Id = 96,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Latvian (Lettish) lv"
                        },
                        new
                        {
                            Id = 97,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Limburgish ( Limburger) li"
                        },
                        new
                        {
                            Id = 98,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Lingala ln"
                        },
                        new
                        {
                            Id = 99,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Lithuanian lt"
                        },
                        new
                        {
                            Id = 100,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Luga-Katanga lu"
                        },
                        new
                        {
                            Id = 101,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Luganda, Ganda lg"
                        },
                        new
                        {
                            Id = 102,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Luxembourgish lb"
                        },
                        new
                        {
                            Id = 103,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Manx gv"
                        },
                        new
                        {
                            Id = 104,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Macedonian mk"
                        },
                        new
                        {
                            Id = 105,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Malagasy mg"
                        },
                        new
                        {
                            Id = 106,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Malay ms"
                        },
                        new
                        {
                            Id = 107,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Malayalam ml"
                        },
                        new
                        {
                            Id = 108,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Maltese mt"
                        },
                        new
                        {
                            Id = 109,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Maori mi"
                        },
                        new
                        {
                            Id = 110,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Marathi mr"
                        },
                        new
                        {
                            Id = 111,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Marshallese mh"
                        },
                        new
                        {
                            Id = 112,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Moldavian mo"
                        },
                        new
                        {
                            Id = 113,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Mongolian mn"
                        },
                        new
                        {
                            Id = 114,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Nauru na"
                        },
                        new
                        {
                            Id = 115,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Navajo nv"
                        },
                        new
                        {
                            Id = 116,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Ndonga ng"
                        },
                        new
                        {
                            Id = 117,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Northern Ndebele nd"
                        },
                        new
                        {
                            Id = 118,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Nepali ne"
                        },
                        new
                        {
                            Id = 119,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Norwegian no"
                        },
                        new
                        {
                            Id = 120,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Norwegian bokmål nb"
                        },
                        new
                        {
                            Id = 121,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Norwegian nynorsk nn"
                        },
                        new
                        {
                            Id = 122,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Nuosu ii"
                        },
                        new
                        {
                            Id = 123,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Occitan oc"
                        },
                        new
                        {
                            Id = 124,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Ojibwe oj"
                        },
                        new
                        {
                            Id = 125,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Old Church Slavonic, Old Bulgarian cu"
                        },
                        new
                        {
                            Id = 126,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Oriya or"
                        },
                        new
                        {
                            Id = 127,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Oromo (Afaan Oromo) om"
                        },
                        new
                        {
                            Id = 128,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Ossetian os"
                        },
                        new
                        {
                            Id = 129,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Pāli pi"
                        },
                        new
                        {
                            Id = 130,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Pashto, Pushto ps"
                        },
                        new
                        {
                            Id = 131,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Persian (Farsi) fa"
                        },
                        new
                        {
                            Id = 132,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Polish pl"
                        },
                        new
                        {
                            Id = 133,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Portuguese pt"
                        },
                        new
                        {
                            Id = 134,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Punjabi (Eastern) pa"
                        },
                        new
                        {
                            Id = 135,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Quechua qu"
                        },
                        new
                        {
                            Id = 136,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Romansh rm"
                        },
                        new
                        {
                            Id = 137,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Romanian ro"
                        },
                        new
                        {
                            Id = 138,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Russian ru"
                        },
                        new
                        {
                            Id = 139,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sami se"
                        },
                        new
                        {
                            Id = 140,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Samoan sm"
                        },
                        new
                        {
                            Id = 141,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sango sg"
                        },
                        new
                        {
                            Id = 142,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sanskrit sa"
                        },
                        new
                        {
                            Id = 143,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Serbian sr"
                        },
                        new
                        {
                            Id = 144,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Serbo-Croatian sh"
                        },
                        new
                        {
                            Id = 145,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sesotho st"
                        },
                        new
                        {
                            Id = 146,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Setswana tn"
                        },
                        new
                        {
                            Id = 147,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Shona sn"
                        },
                        new
                        {
                            Id = 148,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sichuan Yi ii"
                        },
                        new
                        {
                            Id = 149,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sindhi sd"
                        },
                        new
                        {
                            Id = 150,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sinhalese si"
                        },
                        new
                        {
                            Id = 151,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Siswati ss"
                        },
                        new
                        {
                            Id = 152,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Slovak sk"
                        },
                        new
                        {
                            Id = 153,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Slovenian sl"
                        },
                        new
                        {
                            Id = 154,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Somali so"
                        },
                        new
                        {
                            Id = 155,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Southern Ndebele nr"
                        },
                        new
                        {
                            Id = 156,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Spanish es"
                        },
                        new
                        {
                            Id = 157,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Sundanese su"
                        },
                        new
                        {
                            Id = 158,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Swahili (Kiswahili) sw"
                        },
                        new
                        {
                            Id = 159,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Swati ss"
                        },
                        new
                        {
                            Id = 160,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Swedish sv"
                        },
                        new
                        {
                            Id = 161,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tagalog tl"
                        },
                        new
                        {
                            Id = 162,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tahitian ty"
                        },
                        new
                        {
                            Id = 163,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tajik tg"
                        },
                        new
                        {
                            Id = 164,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tamil ta"
                        },
                        new
                        {
                            Id = 165,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tatar tt"
                        },
                        new
                        {
                            Id = 166,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Telugu te"
                        },
                        new
                        {
                            Id = 167,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Thai th"
                        },
                        new
                        {
                            Id = 168,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tibetan bo"
                        },
                        new
                        {
                            Id = 169,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tigrinya ti"
                        },
                        new
                        {
                            Id = 170,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tonga to"
                        },
                        new
                        {
                            Id = 171,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Tsonga ts"
                        },
                        new
                        {
                            Id = 172,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Turkish tr"
                        },
                        new
                        {
                            Id = 173,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Turkmen tk"
                        },
                        new
                        {
                            Id = 174,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Twi tw"
                        },
                        new
                        {
                            Id = 175,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Uyghur ug"
                        },
                        new
                        {
                            Id = 176,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Ukrainian uk"
                        },
                        new
                        {
                            Id = 177,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Urdu ur"
                        },
                        new
                        {
                            Id = 178,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Uzbek uz"
                        },
                        new
                        {
                            Id = 179,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Venda ve"
                        },
                        new
                        {
                            Id = 180,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Vietnamese vi"
                        },
                        new
                        {
                            Id = 181,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Volapük vo"
                        },
                        new
                        {
                            Id = 182,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Wallon wa"
                        },
                        new
                        {
                            Id = 183,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Welsh cy"
                        },
                        new
                        {
                            Id = 184,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Wolof wo"
                        },
                        new
                        {
                            Id = 185,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Western Frisian fy"
                        },
                        new
                        {
                            Id = 186,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Xhosa xh"
                        },
                        new
                        {
                            Id = 187,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Yiddish yi, ji"
                        },
                        new
                        {
                            Id = 188,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Yoruba yo"
                        },
                        new
                        {
                            Id = 189,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Zhuang, Chuang za"
                        },
                        new
                        {
                            Id = 190,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Zulu zu"
                        },
                        new
                        {
                            Id = 191,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            TargetLanguage = "Abkhazian ab"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
