// <auto-generated />
using ConsoleArchivist.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleArchivist.Migrations
{
    [DbContext(typeof(ArchivistDbContext))]
    [Migration("20240201224927_CreateSeedDataWithLanguagesNames")]
    partial class CreateSeedDataWithLanguagesNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("ConsoleArchivist.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GPTTranslationInYaml")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InGitHub")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsToSentToGitHub")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LangTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Árabe - Arab"
                        },
                        new
                        {
                            Id = 2,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Armênio - Armn"
                        },
                        new
                        {
                            Id = 3,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Assamês - Beng"
                        },
                        new
                        {
                            Id = 4,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Azeri (Latim) - Latn"
                        },
                        new
                        {
                            Id = 5,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Azeri (Cirílico) - Cyrl"
                        },
                        new
                        {
                            Id = 6,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Basco - Latn"
                        },
                        new
                        {
                            Id = 7,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Bielorrusso - Cyrl"
                        },
                        new
                        {
                            Id = 8,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Bengali - Beng"
                        },
                        new
                        {
                            Id = 9,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Búlgaro - Cyrl"
                        },
                        new
                        {
                            Id = 10,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Birmanês - Mymr"
                        },
                        new
                        {
                            Id = 11,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Catalão - Latn"
                        },
                        new
                        {
                            Id = 12,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Cherokee - Cher"
                        },
                        new
                        {
                            Id = 13,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Chinês (Simplificado) - Hans"
                        },
                        new
                        {
                            Id = 14,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Chinês (Tradicional) - Hant"
                        },
                        new
                        {
                            Id = 15,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Copta - Copt"
                        },
                        new
                        {
                            Id = 16,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Croata - Latn"
                        },
                        new
                        {
                            Id = 17,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Tcheco - Latn"
                        },
                        new
                        {
                            Id = 18,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Dinamarquês - Latn"
                        },
                        new
                        {
                            Id = 19,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Divehi - Thaa"
                        },
                        new
                        {
                            Id = 20,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Holandês - Latn"
                        },
                        new
                        {
                            Id = 21,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Inglês - Latn"
                        },
                        new
                        {
                            Id = 22,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Esperanto - Latn"
                        },
                        new
                        {
                            Id = 23,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Estoniano - Latn"
                        },
                        new
                        {
                            Id = 24,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Éwé - Latn"
                        },
                        new
                        {
                            Id = 25,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Faroês - Latn"
                        },
                        new
                        {
                            Id = 26,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Filipino - Latn"
                        },
                        new
                        {
                            Id = 27,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Finlandês - Latn"
                        },
                        new
                        {
                            Id = 28,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Francês - Latn"
                        },
                        new
                        {
                            Id = 29,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Frísio - Latn"
                        },
                        new
                        {
                            Id = 30,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Gaélico (Escocês) - Latn"
                        },
                        new
                        {
                            Id = 31,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Georgiano - Geor"
                        },
                        new
                        {
                            Id = 32,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Alemão - Latn"
                        },
                        new
                        {
                            Id = 33,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Grego - Grek"
                        },
                        new
                        {
                            Id = 34,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Groenlandês - Latn"
                        },
                        new
                        {
                            Id = 35,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Gujarati - Gujr"
                        },
                        new
                        {
                            Id = 36,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Hausa - Latn"
                        },
                        new
                        {
                            Id = 37,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Hebraico - Hebr"
                        },
                        new
                        {
                            Id = 38,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Hindi - Deva"
                        },
                        new
                        {
                            Id = 39,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Húngaro - Latn"
                        },
                        new
                        {
                            Id = 40,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Islandês - Latn"
                        },
                        new
                        {
                            Id = 41,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Igbo - Latn"
                        },
                        new
                        {
                            Id = 42,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Indonésio - Latn"
                        },
                        new
                        {
                            Id = 43,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Irlandês - Latn"
                        },
                        new
                        {
                            Id = 44,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Italiano - Latn"
                        },
                        new
                        {
                            Id = 45,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Japonês - Jpan (abrangendo Kanji, Hiragana, Katakana)"
                        },
                        new
                        {
                            Id = 46,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Javanês (Latim) - Latn"
                        },
                        new
                        {
                            Id = 47,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Kannada - Knda"
                        },
                        new
                        {
                            Id = 48,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Cazaque (Cirílico) - Cyrl"
                        },
                        new
                        {
                            Id = 49,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Cazaque (Latim) - Latn"
                        },
                        new
                        {
                            Id = 50,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Khmer - Khmr"
                        },
                        new
                        {
                            Id = 51,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Coreano - Hang"
                        },
                        new
                        {
                            Id = 52,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Curdo (Latim) - Latn"
                        },
                        new
                        {
                            Id = 53,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Quirguiz (Cirílico) - Cyrl"
                        },
                        new
                        {
                            Id = 54,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Lao - Laoo"
                        },
                        new
                        {
                            Id = 55,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Latim - Latn"
                        },
                        new
                        {
                            Id = 56,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Letão - Latn"
                        },
                        new
                        {
                            Id = 57,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Lituano - Latn"
                        },
                        new
                        {
                            Id = 58,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Macedônio - Cyrl"
                        },
                        new
                        {
                            Id = 59,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Malaiala - Mlym"
                        },
                        new
                        {
                            Id = 60,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Malaio (Latim) - Latn"
                        },
                        new
                        {
                            Id = 61,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Malaio (Árabe) - Arab"
                        },
                        new
                        {
                            Id = 62,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Maldiviano - Thaa"
                        },
                        new
                        {
                            Id = 63,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Maltês - Latn"
                        },
                        new
                        {
                            Id = 64,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Maori - Latn"
                        },
                        new
                        {
                            Id = 65,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Marathi - Deva"
                        },
                        new
                        {
                            Id = 66,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Mongol (Cirílico) - Cyrl"
                        },
                        new
                        {
                            Id = 67,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Nepalês - Deva"
                        },
                        new
                        {
                            Id = 68,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Norueguês - Latn"
                        },
                        new
                        {
                            Id = 69,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Oriya - Orya"
                        },
                        new
                        {
                            Id = 70,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Oromo - Latn"
                        },
                        new
                        {
                            Id = 71,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Pashto - Arab"
                        },
                        new
                        {
                            Id = 72,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Persa - Arab"
                        },
                        new
                        {
                            Id = 73,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Polonês - Latn"
                        },
                        new
                        {
                            Id = 74,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Português - Latn"
                        },
                        new
                        {
                            Id = 75,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Punjabi (Gurmukhi) - Guru"
                        },
                        new
                        {
                            Id = 76,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Punjabi (Árabe) - Arab"
                        },
                        new
                        {
                            Id = 77,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Romeno - Latn"
                        },
                        new
                        {
                            Id = 78,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Russo - Cyrl"
                        },
                        new
                        {
                            Id = 79,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Sânscrito - Deva"
                        },
                        new
                        {
                            Id = 80,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Sérvio (Latim) - Latn"
                        },
                        new
                        {
                            Id = 81,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Sindhi - Arab"
                        },
                        new
                        {
                            Id = 82,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Cingalês - Sinh"
                        },
                        new
                        {
                            Id = 83,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Eslovaco - Latn"
                        },
                        new
                        {
                            Id = 84,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Esloveno - Latn"
                        },
                        new
                        {
                            Id = 85,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Somali - Latn"
                        },
                        new
                        {
                            Id = 86,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Espanhol - Latn"
                        },
                        new
                        {
                            Id = 87,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Suaíli - Latn"
                        },
                        new
                        {
                            Id = 88,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Sueco - Latn"
                        },
                        new
                        {
                            Id = 89,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Tâmil - Taml"
                        },
                        new
                        {
                            Id = 90,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Tártaro (Cirílico) - Cyrl"
                        },
                        new
                        {
                            Id = 91,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Telugu - Telu"
                        },
                        new
                        {
                            Id = 92,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Tailandês - Thai"
                        },
                        new
                        {
                            Id = 93,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Tibetano - Tibt"
                        },
                        new
                        {
                            Id = 94,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Tigrinya - Ethi"
                        },
                        new
                        {
                            Id = 95,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Turco - Latn"
                        },
                        new
                        {
                            Id = 96,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Turcomano (Latim) - Latn"
                        },
                        new
                        {
                            Id = 97,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Ucraniano - Cyrl"
                        },
                        new
                        {
                            Id = 98,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Urdu - Arab"
                        },
                        new
                        {
                            Id = 99,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Uzbeque (Latim) - Latn"
                        },
                        new
                        {
                            Id = 100,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Uzbeque (Cirílico) - Cyrl"
                        },
                        new
                        {
                            Id = 101,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Vietnamita - Latn"
                        },
                        new
                        {
                            Id = 102,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Galês - Latn"
                        },
                        new
                        {
                            Id = 103,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Xhosa - Latn"
                        },
                        new
                        {
                            Id = 104,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Iídiche - Hebr"
                        },
                        new
                        {
                            Id = 105,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Iorubá - Latn"
                        },
                        new
                        {
                            Id = 106,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Zulu - Latn"
                        },
                        new
                        {
                            Id = 107,
                            InGitHub = false,
                            IsToSentToGitHub = false,
                            Name = "Sérvio (Cirílico) - Cyrl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
