using ConsoleArchivist.Models.Db;
using Microsoft.EntityFrameworkCore;

namespace ConsoleArchivist.Database;

public class ArchivistDbContext(DbContextOptions<ArchivistDbContext> options) : DbContext(options)
{
    public DbSet<Translation> Translations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Translation>().Property(e => e.IsToSentToGitHub).HasDefaultValue(true);
        modelBuilder.Entity<Translation>().Property(e => e.InGitHub).HasDefaultValue(false);

        modelBuilder.Entity<Translation>().HasData(
            new Translation { Id = 1, TargetLanguage = "Afar aa" },
            new Translation { Id = 2, TargetLanguage = "Afrikaans af" },
            new Translation { Id = 3, TargetLanguage = "Akan ak" },
            new Translation { Id = 4, TargetLanguage = "Albanian sq" },
            new Translation { Id = 5, TargetLanguage = "Amharic am" },
            new Translation { Id = 6, TargetLanguage = "Arabic ar" },
            new Translation { Id = 7, TargetLanguage = "Aragonese an" },
            new Translation { Id = 8, TargetLanguage = "Armenian hy" },
            new Translation { Id = 9, TargetLanguage = "Assamese as" },
            new Translation { Id = 10, TargetLanguage = "Avaric av" },
            new Translation { Id = 11, TargetLanguage = "Avestan ae" },
            new Translation { Id = 12, TargetLanguage = "Aymara ay" },
            new Translation { Id = 13, TargetLanguage = "Azerbaijani az" },
            new Translation { Id = 14, TargetLanguage = "Bambara bm" },
            new Translation { Id = 15, TargetLanguage = "Bashkir ba" },
            new Translation { Id = 16, TargetLanguage = "Basque eu" },
            new Translation { Id = 17, TargetLanguage = "Belarusian be" },
            new Translation { Id = 18, TargetLanguage = "Bengali (Bangla) bn" },
            new Translation { Id = 19, TargetLanguage = "Bihari bh" },
            new Translation { Id = 20, TargetLanguage = "Bislama bi" },
            new Translation { Id = 21, TargetLanguage = "Bosnian bs" },
            new Translation { Id = 22, TargetLanguage = "Breton br" },
            new Translation { Id = 23, TargetLanguage = "Bulgarian bg" },
            new Translation { Id = 24, TargetLanguage = "Burmese my" },
            new Translation { Id = 25, TargetLanguage = "Catalan ca" },
            new Translation { Id = 26, TargetLanguage = "Chamorro ch" },
            new Translation { Id = 27, TargetLanguage = "Chechen ce" },
            new Translation { Id = 28, TargetLanguage = "Chichewa, Chewa, Nyanja ny" },
            new Translation { Id = 29, TargetLanguage = "Chinese zh" },
            new Translation { Id = 30, TargetLanguage = "Chinese (Simplified) zh-Hans" },
            new Translation { Id = 31, TargetLanguage = "Chinese (Traditional) zh-Hant" },
            new Translation { Id = 32, TargetLanguage = "Chuvash cv" },
            new Translation { Id = 33, TargetLanguage = "Cornish kw" },
            new Translation { Id = 34, TargetLanguage = "Corsican co" },
            new Translation { Id = 35, TargetLanguage = "Cree cr" },
            new Translation { Id = 36, TargetLanguage = "Croatian hr" },
            new Translation { Id = 37, TargetLanguage = "Czech cs" },
            new Translation { Id = 38, TargetLanguage = "Danish da" },
            new Translation { Id = 39, TargetLanguage = "Divehi, Dhivehi, Maldivian dv" },
            new Translation { Id = 40, TargetLanguage = "Dutch nl" },
            new Translation { Id = 41, TargetLanguage = "Dzongkha dz" },
            new Translation { Id = 42, TargetLanguage = "English en" },
            new Translation { Id = 43, TargetLanguage = "Esperanto eo" },
            new Translation { Id = 44, TargetLanguage = "Estonian et" },
            new Translation { Id = 45, TargetLanguage = "Ewe ee" },
            new Translation { Id = 46, TargetLanguage = "Faroese fo" },
            new Translation { Id = 47, TargetLanguage = "Fijian fj" },
            new Translation { Id = 48, TargetLanguage = "Finnish fi" },
            new Translation { Id = 49, TargetLanguage = "French fr" },
            new Translation { Id = 50, TargetLanguage = "Fula, Fulah, Pulaar, Pular ff" },
            new Translation { Id = 51, TargetLanguage = "Galician gl" },
            new Translation { Id = 52, TargetLanguage = "Gaelic (Scottish) gd" },
            new Translation { Id = 53, TargetLanguage = "Gaelic (Manx) gv" },
            new Translation { Id = 54, TargetLanguage = "Georgian ka" },
            new Translation { Id = 55, TargetLanguage = "German de" },
            new Translation { Id = 56, TargetLanguage = "Greek el" },
            new Translation { Id = 57, TargetLanguage = "Greenlandic kl" },
            new Translation { Id = 58, TargetLanguage = "Guarani gn" },
            new Translation { Id = 59, TargetLanguage = "Gujarati gu" },
            new Translation { Id = 60, TargetLanguage = "Haitian Creole ht" },
            new Translation { Id = 61, TargetLanguage = "Hausa ha" },
            new Translation { Id = 62, TargetLanguage = "Hebrew he" },
            new Translation { Id = 63, TargetLanguage = "Herero hz" },
            new Translation { Id = 64, TargetLanguage = "Hindi hi" },
            new Translation { Id = 65, TargetLanguage = "Hiri Motu ho" },
            new Translation { Id = 66, TargetLanguage = "Hungarian hu" },
            new Translation { Id = 67, TargetLanguage = "Icelandic is" },
            new Translation { Id = 68, TargetLanguage = "Ido io" },
            new Translation { Id = 69, TargetLanguage = "Igbo ig" },
            new Translation { Id = 70, TargetLanguage = "Indonesian id, in" },
            new Translation { Id = 71, TargetLanguage = "Interlingua ia" },
            new Translation { Id = 72, TargetLanguage = "Interlingue ie" },
            new Translation { Id = 73, TargetLanguage = "Inuktitut iu" },
            new Translation { Id = 74, TargetLanguage = "Inupiak ik" },
            new Translation { Id = 75, TargetLanguage = "Irish ga" },
            new Translation { Id = 76, TargetLanguage = "Italian it" },
            new Translation { Id = 77, TargetLanguage = "Japanese ja" },
            new Translation { Id = 78, TargetLanguage = "Javanese jv" },
            new Translation { Id = 79, TargetLanguage = "Kalaallisut, Greenlandic kl" },
            new Translation { Id = 80, TargetLanguage = "Kannada kn" },
            new Translation { Id = 81, TargetLanguage = "Kanuri kr" },
            new Translation { Id = 82, TargetLanguage = "Kashmiri ks" },
            new Translation { Id = 83, TargetLanguage = "Kazakh kk" },
            new Translation { Id = 84, TargetLanguage = "Khmer km" },
            new Translation { Id = 85, TargetLanguage = "Kikuyu ki" },
            new Translation { Id = 86, TargetLanguage = "Kinyarwanda (Rwanda) rw" },
            new Translation { Id = 87, TargetLanguage = "Kirundi rn" },
            new Translation { Id = 88, TargetLanguage = "Kyrgyz ky" },
            new Translation { Id = 89, TargetLanguage = "Komi kv" },
            new Translation { Id = 90, TargetLanguage = "Kongo kg" },
            new Translation { Id = 91, TargetLanguage = "Korean ko" },
            new Translation { Id = 92, TargetLanguage = "Kurdish ku" },
            new Translation { Id = 93, TargetLanguage = "Kwanyama kj" },
            new Translation { Id = 94, TargetLanguage = "Lao lo" },
            new Translation { Id = 95, TargetLanguage = "Latin la" },
            new Translation { Id = 96, TargetLanguage = "Latvian (Lettish) lv" },
            new Translation { Id = 97, TargetLanguage = "Limburgish ( Limburger) li" },
            new Translation { Id = 98, TargetLanguage = "Lingala ln" },
            new Translation { Id = 99, TargetLanguage = "Lithuanian lt" },
            new Translation { Id = 100, TargetLanguage = "Luga-Katanga lu" },
            new Translation { Id = 101, TargetLanguage = "Luganda, Ganda lg" },
            new Translation { Id = 102, TargetLanguage = "Luxembourgish lb" },
            new Translation { Id = 103, TargetLanguage = "Manx gv" },
            new Translation { Id = 104, TargetLanguage = "Macedonian mk" },
            new Translation { Id = 105, TargetLanguage = "Malagasy mg" },
            new Translation { Id = 106, TargetLanguage = "Malay ms" },
            new Translation { Id = 107, TargetLanguage = "Malayalam ml" },
            new Translation { Id = 108, TargetLanguage = "Maltese mt" },
            new Translation { Id = 109, TargetLanguage = "Maori mi" },
            new Translation { Id = 110, TargetLanguage = "Marathi mr" },
            new Translation { Id = 111, TargetLanguage = "Marshallese mh" },
            new Translation { Id = 112, TargetLanguage = "Moldavian mo" },
            new Translation { Id = 113, TargetLanguage = "Mongolian mn" },
            new Translation { Id = 114, TargetLanguage = "Nauru na" },
            new Translation { Id = 115, TargetLanguage = "Navajo nv" },
            new Translation { Id = 116, TargetLanguage = "Ndonga ng" },
            new Translation { Id = 117, TargetLanguage = "Northern Ndebele nd" },
            new Translation { Id = 118, TargetLanguage = "Nepali ne" },
            new Translation { Id = 119, TargetLanguage = "Norwegian no" },
            new Translation { Id = 120, TargetLanguage = "Norwegian bokmål nb" },
            new Translation { Id = 121, TargetLanguage = "Norwegian nynorsk nn" },
            new Translation { Id = 122, TargetLanguage = "Nuosu ii" },
            new Translation { Id = 123, TargetLanguage = "Occitan oc" },
            new Translation { Id = 124, TargetLanguage = "Ojibwe oj" },
            new Translation { Id = 125, TargetLanguage = "Old Church Slavonic, Old Bulgarian cu" },
            new Translation { Id = 126, TargetLanguage = "Oriya or" },
            new Translation { Id = 127, TargetLanguage = "Oromo (Afaan Oromo) om" },
            new Translation { Id = 128, TargetLanguage = "Ossetian os" },
            new Translation { Id = 129, TargetLanguage = "Pāli pi" },
            new Translation { Id = 130, TargetLanguage = "Pashto, Pushto ps" },
            new Translation { Id = 131, TargetLanguage = "Persian (Farsi) fa" },
            new Translation { Id = 132, TargetLanguage = "Polish pl" },
            new Translation { Id = 133, TargetLanguage = "Portuguese pt" },
            new Translation { Id = 134, TargetLanguage = "Punjabi (Eastern) pa" },
            new Translation { Id = 135, TargetLanguage = "Quechua qu" },
            new Translation { Id = 136, TargetLanguage = "Romansh rm" },
            new Translation { Id = 137, TargetLanguage = "Romanian ro" },
            new Translation { Id = 138, TargetLanguage = "Russian ru" },
            new Translation { Id = 139, TargetLanguage = "Sami se" },
            new Translation { Id = 140, TargetLanguage = "Samoan sm" },
            new Translation { Id = 141, TargetLanguage = "Sango sg" },
            new Translation { Id = 142, TargetLanguage = "Sanskrit sa" },
            new Translation { Id = 143, TargetLanguage = "Serbian sr" },
            new Translation { Id = 144, TargetLanguage = "Serbo-Croatian sh" },
            new Translation { Id = 145, TargetLanguage = "Sesotho st" },
            new Translation { Id = 146, TargetLanguage = "Setswana tn" },
            new Translation { Id = 147, TargetLanguage = "Shona sn" },
            new Translation { Id = 148, TargetLanguage = "Sichuan Yi ii" },
            new Translation { Id = 149, TargetLanguage = "Sindhi sd" },
            new Translation { Id = 150, TargetLanguage = "Sinhalese si" },
            new Translation { Id = 151, TargetLanguage = "Siswati ss" },
            new Translation { Id = 152, TargetLanguage = "Slovak sk" },
            new Translation { Id = 153, TargetLanguage = "Slovenian sl" },
            new Translation { Id = 154, TargetLanguage = "Somali so" },
            new Translation { Id = 155, TargetLanguage = "Southern Ndebele nr" },
            new Translation { Id = 156, TargetLanguage = "Spanish es" },
            new Translation { Id = 157, TargetLanguage = "Sundanese su" },
            new Translation { Id = 158, TargetLanguage = "Swahili (Kiswahili) sw" },
            new Translation { Id = 159, TargetLanguage = "Swati ss" },
            new Translation { Id = 160, TargetLanguage = "Swedish sv" },
            new Translation { Id = 161, TargetLanguage = "Tagalog tl" },
            new Translation { Id = 162, TargetLanguage = "Tahitian ty" },
            new Translation { Id = 163, TargetLanguage = "Tajik tg" },
            new Translation { Id = 164, TargetLanguage = "Tamil ta" },
            new Translation { Id = 165, TargetLanguage = "Tatar tt" },
            new Translation { Id = 166, TargetLanguage = "Telugu te" },
            new Translation { Id = 167, TargetLanguage = "Thai th" },
            new Translation { Id = 168, TargetLanguage = "Tibetan bo" },
            new Translation { Id = 169, TargetLanguage = "Tigrinya ti" },
            new Translation { Id = 170, TargetLanguage = "Tonga to" },
            new Translation { Id = 171, TargetLanguage = "Tsonga ts" },
            new Translation { Id = 172, TargetLanguage = "Turkish tr" },
            new Translation { Id = 173, TargetLanguage = "Turkmen tk" },
            new Translation { Id = 174, TargetLanguage = "Twi tw" },
            new Translation { Id = 175, TargetLanguage = "Uyghur ug" },
            new Translation { Id = 176, TargetLanguage = "Ukrainian uk" },
            new Translation { Id = 177, TargetLanguage = "Urdu ur" },
            new Translation { Id = 178, TargetLanguage = "Uzbek uz" },
            new Translation { Id = 179, TargetLanguage = "Venda ve" },
            new Translation { Id = 180, TargetLanguage = "Vietnamese vi" },
            new Translation { Id = 181, TargetLanguage = "Volapük vo" },
            new Translation { Id = 182, TargetLanguage = "Wallon wa" },
            new Translation { Id = 183, TargetLanguage = "Welsh cy" },
            new Translation { Id = 184, TargetLanguage = "Wolof wo" },
            new Translation { Id = 185, TargetLanguage = "Western Frisian fy" },
            new Translation { Id = 186, TargetLanguage = "Xhosa xh" },
            new Translation { Id = 187, TargetLanguage = "Yiddish yi, ji" },
            new Translation { Id = 188, TargetLanguage = "Yoruba yo" },
            new Translation { Id = 189, TargetLanguage = "Zhuang, Chuang za" },
            new Translation { Id = 190, TargetLanguage = "Zulu zu" },
            new Translation { Id = 191, TargetLanguage = "Abkhazian ab" }
        );

        base.OnModelCreating(modelBuilder);
    }
}
